### ISSUE TITLE
Extend favicon partial

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#102]
See this change here. Consider updates for improved experience and addition of a manifest.

https://github.com/linuxlefty/LinuxLefty-Theme/commit/6cd1d71ec460c3846efd23a6e7896e57a454e9ab

```
+<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
+<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
+<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
+<link rel="manifest" href="/site.webmanifest">
+<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
+<meta name="msapplication-TileColor" content="#da532c">
+<meta name="theme-color" content="#ffffff">
```

**Comment by linuxlefty** [comment]
Hey! I just noticed that you referenced my fork, I'm honored :).

I would just replace the default favicon partial with the updated link/meta fields. Personally, if I make custom changes, I'm not expecting backwards compability in matters like this, but that's just me.

The other option would be to use actual files instead embedded data. That way the favicons can be updated without having to change any template files.
