### ISSUE TITLE
Weird Bug with Fuzzy Search

### ISSUE THREAD

**Issue by dalliard** [comfusion/after-dark#104]
I am using a different theme, but tried to implement the fuzzy search from after-dark and have a weird bug when using the search on my site. Maybe someone can look into it and sees the mistake I made.

## What I did
I created the following files:
`content/page/suche.md` with `layout: search` *([Link to the file](https://github.com/dalliard/blog/blob/master/layouts/_default/search.html))*
`layouts/_default/search.html` *([Link to the file](https://github.com/dalliard/blog/blob/master/content/page/suche.md))*

Added to `config.toml`: 
````
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
````

## The Bug
1. Go to [https://dalliard.ch/suche/](https://dalliard.ch/suche/)
2. Type `imp` into the search field. Then you see the first result is **Impressum** and the second is **Impulskäufe vermeiden** with the corresponding excerpts.
3. Now add to `imp` a `u` so you search for `impu`. Now the header of the results stay the same but the excerpts change. **Expected:** The title also changes.

I thought maybe it's because I called the page `suche`instead of `search`, but that didn't solve the problem. Weird is also, that the link changes correctly, just the titles don't. Has someone an idea what I am doing wrong or is this really a bug? Thanks!

**Comment by jhabdas** [comment]
Thanks for opening this @dalliard. I've seen this bug in the search layout as well but don't have time to look into it in detail right now. Could you try installing the Vue debugger and inspecting the state of the search results after the change? If it turns out the model (state) is correct but the view (document) isn't updated there's some kind of binding glitch or bug in Vue or the way I'm implementing it.

**Comment by jhabdas** [comment]
@liara just wanted to call this issue to your attention to ask if you've also seen this bug. I noticed it soon after adding the search layout but figured it was a browser bug, framework bug or edge case of some kind. right now the workaround is to simply refresh the page but it would be nice if one didn't have to.

**Comment by liara** [comment]
@jhabdas I see it too. The link changes, but not the title, as @dalliard  pointed out. Will have a look, maybe something comes to mind.

**Comment by liara** [comment]
I think adding v-html to the url in line 29 of search.html fixes the issue. Like:

```
-<h2 itemprop="name"><a :href="result.item.url">{ result.item.title }</a></h2>
+<h2 itemprop="name"><a :href="result.item.url"><span v-html="result.item.title"></span></a></h2>
```
Can you confirm @jhabdas,  @dalliard?

**Comment by dalliard** [comment]
Yes, it seems to work for me now! I created a pull request #105.
