### ISSUE TITLE
Move theme out of GitHub

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#106]
Hugo theme script supports GitLab I believe. It's time to move now that GitHub sold out.

**Update:** Fool me once, shame on you. Fool me twice… https://github.com/comfusion/after-dark/issues/106#issuecomment-403279521

**Comment by pbuzdin** [comment]
Why?


ср, 6 июн. 2018 г., 8:16 Josh Habdas <notifications@github.com>:

**Comment by liara** [comment]
We can't escape, they are all around us :alien:  GitLab is still on Azure, but moving to Google https://venturebeat.com/2018/04/06/why-and-how-gitlab-abandoned-microsoft-azure-for-google-cloud/
gitgud, notabug, teknik, bitbucket maybe? :P

**Comment by jhabdas** [comment]
@pbuzdin for me it presents a great opportunity to get reorganized, a fresh start, try something new (innovative) and retool my workflow a bit for efficiency. I'm also not too keen on large, multinational corporations having control over my source code. As with Facebook they seem innocent but the end game is always profit.

**Comment by jhabdas** [comment]
@liara thanks for the list I'll be sure to investigate each option before the move. I'm not opposed to a self-hosted instance if it feels right. Tossing Gitea and maybe GitChain and IPFS in the mix too. 👾

**Comment by jhabdas** [comment]
Hugo is ready. Note I may change my mind but change is a natural thing https://github.com/gohugoio/hugoThemes/issues/371

**Comment by jhabdas** [comment]
Took a look at GitLab. Don't care for the UI really. Closing this as not worth the effort.

**Comment by jhabdas** [comment]
Bottom line: If Linux Foundation moves, we'll move.

**Comment by jhabdas** [comment]
I'm still conflicted. Reopened

**Comment by jhabdas** [comment]
Nah

**Comment by jhabdas** [comment]
Quick update here. All previously verified commits in this repo have been unverified since the acquisition. These commits were signed with PGP and have since been unsigned by no action of my own.

**Comment by jhabdas** [comment]
According to my research MicroHub had revoked my proofs as a result of not having an unreachable email address. As such further development will be taking place elsewhere. Been fun y'all!!

**Comment by jhabdas** [comment]
https://github.com/gitchain/gitchain

**Comment by jhabdas** [comment]
I was looking at this last year and it looks like someone is running a Kickstarter to get it going again. Not sure how far they'll get but it's worth checking out: https://github.com/gitchain/gitchain

As for the time being I'm going to plan on moving my sources to a private Gitea node on a VPS. If possible I'll keep this repo here as a mirror of the official After Dark, which is about to get a whole lot darker.

**Comment by jhabdas** [comment]
I was looking at this last year and it looks like someone is running a Kickstarter to get it going again. Not sure how far they'll get but it's worth checking out: https://github.com/gitchain/gitchain

As for the time being I'm going to plan on moving my sources to a [Gitea](https://gitea.io/en-US/) node hosted on a private VPS. If possible I'll keep this repo here as a mirror of the official After Dark. Cheers.

**Comment by jhabdas** [comment]
Self-hosted Gitea server is up at [http://git.habd.as:3000](http://git.habd.as:3000) which will be the new canonical home for After Dark. After [rewriting author history](https://help.github.com/articles/changing-author-info/) I was able to restore my PGP verification. With a little more work I'll ping the Hugo team and let them know what I'm up to. And though I could mirror on GitHub they don't make it very easy to do so, so the jury is still out on whether or not this repo will be maintained as I continue wrenching on this theme.

**Comment by liara** [comment]
Good. Gitea sounds like a good choice, also nice theme:)

**Comment by jhabdas** [comment]
Started a tool to make self-hosted Gitea ridiculously easy to set up in a scalable way:

http://git.habd.as:3000/jhabdas/tea-party

Tomorrow will work on getting TLS certs in place and automated and shuffle some containers around on my VPS so I can move the Gitea app onto port 80. Big plans ahead.

**Comment by jhabdas** [comment]
After Dark has a new home:
https://git.habd.as/comfusion/after-dark

In order to restore the commit SHAs I rewrite history using my new email address. Please note if you're forked off After Dark this will royally screw you up. And for that I'm sorry.

In case anyone is interested in hosting their own Gitea server I've created the following project which I'm dogfooding on `git.habd.as`: https://git.habd.as/comfusion/tea-party

Next steps:

1. Update theme in the `hugoThemes` repo.
2. Update images in the `README` to use the absolute path on the new server.
3. Deprecate or mirror this repo off the new canonical source.
