### ISSUE TITLE
Web Notifications

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#107]
Consider a friendly (read: non-modal) solution to allow publishers to notify their readers when new content is published. As worth all things after dark it should be Spartan and leverage web standards as much as possible.

**Comment by jhabdas** [comment]
https://www.w3.org/TR/notifications/

**Comment by pbuzdin** [comment]
https://getbootstrap.com/docs/4.0/components/alerts/

**Comment by jhabdas** [comment]
thanks @pbuzdin. having some kind of snack bar for cookie disclaimers and unobtrusive popups seems like the way to go. will def study what bs4 brings to the table 💪

**Comment by jhabdas** [comment]
![screenshot_20180611_063716](https://user-images.githubusercontent.com/440298/41207085-ff9f63b6-6cfe-11e8-8b6a-02d4becd414c.jpg)

**Comment by jhabdas** [comment]
https://tools.ietf.org/html/draft-ietf-webpush-protocol-12

**Comment by jhabdas** [comment]
Closing this as I'm not planning to implement these in After Dark at this time.
