### ISSUE TITLE
Monero mining

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#108]
Optional with user opt in. Display a snack bar to allow the user to participate or just do it since it'll help push forward ad blocking tech like that in Brave.

<img width="729" alt="screen shot 2018-06-16 at 12 06 13 am" src="https://user-images.githubusercontent.com/440298/41478183-563f992c-70f9-11e8-95df-6f670db70a5b.png">

https://coinhive.com/
https://talk.balibebas.com/t/news-media-paints-coinhive-in-dark-light/104

**Comment by jhabdas** [comment]
\>=] https://btcmanager.com/hackers-earned-over-96-million-by-fraudulently-mining-monero-finds-research/

**Comment by jhabdas** [comment]
https://coinhive.com/

**Comment by jhabdas** [comment]
Holding off on this to gauge user desire. Personally I'm planning on testing this on my own sites and I'm not planning to warn users ahead of time. IMO GDPR is dumb, cookie popups are an extreme annoyance which I don't see lasting too long and the web was built to be free—so we'll let freedom ring should that be the desired course of action.

**Comment by linuxlefty** [comment]
I'd vote :-1: for it. I know it's not the same, but it feels like hijacking a visitors browser. My 2c, anyways

**Comment by jhabdas** [comment]
The same could be said of advertisements as they use resources, attention and time not to mention decreasing privacy.

[I caught](https://talk.balibebas.com/t/telkomsel-hijacks-customer-data-to-serve-mobile-ads/53) one telephony company in Indonesia actually injecting ads on sites, making them appear as if they were coming from the websites themselves. Customer Support never responded to a related inquiry.

With Monero mining we can (optionally) allow users to give back to content publishers without sacrificing time, attention or individual privacy.

What's more this feature could be arranged in such a way users could add their own info to mine directly to their own wallets while browsing while giving publishers a small share if they're feeling generous.

**Comment by jhabdas** [comment]
Glad to hear, @linuxlefty. Or is that Arch Linux Lefty? ;) With theme components now a thing it's time to start breaking stuff apart. If I build this thing correctly I should be able to begin layering stuff in as add-ons so it can be separated into different repos and made reusable across themes confirming to the theme skeleton which after dark was designed to be (for the most part).

**Comment by bgiesing** [comment]
I definitely want this on my site as long as it allows opt-in or opt-out and clearly shows what is happening which it sounds like is your intention.

One suggestion for the snackbar idea, allow specifying a page (either a local page that the person made or some public site) that can show info about the miner. This would add a button to the bar that when clicked takes you to said page. A lot of people hate these miners cause they are misinformed that all of them are bad (when if done right like opt-in they can be good) so allowing the site owner to show a page with more info would be a good idea.

**Comment by jhabdas** [comment]
@bgiesing Thanks for the feedback. I've been researching and prototyping for a week now, learned quite a bit and taken a few missteps. Given Coinhive takes a 30% cut off publisher rev I've been laser focused on allowing users to specify their own mining pools while still taking advantage of the power WebAssembly brings to the browser.

Re: Misinformation I [couldn't agree more](https://talk.balibebas.com/t/news-media-paints-coinhive-in-dark-light/104).

**Comment by jhabdas** [comment]
Quick update here. Discovered a donation supported webminer with a proxy server capable of running WebAssembly in the browser. I've linked out to the source code here: https://t.me/paranoiac. I'm currently working on getting the miner up and running with docker compose so I can release a low-friction set-up for publishers.

**Comment by jhabdas** [comment]
Quick update here. Discovered a donation supported webminer with a proxy server capable of running WebAssembly in the browser. I've linked out to the source code here: https://t.me/paranoiac. I'm currently working on getting the miner up and running with docker compose so I can release a low-friction set-up for publishers.

This setup will allow authors to pull an additional 25–30% of mining profits compared with Coinhive and depending on pool.

**Comment by jhabdas** [comment]
Oops I deleted someone's comment accidentally after GH threw a 404 while trying to delete some other info. In light of the fact GH is no longer verifying my PGP-signed commits I'm afraid development for this feature is going to be anonymous. As such I'm closing this issue. Thanks!

**Comment by jhabdas** [comment]
Version `5.0.0` of After Dark introduces a [module system](https://git.habd.as/comfusion/after-dark#module-system) which lays the foundation for various add-ons, the first of which the replacement of Google Analytics with [Fathom](https://usefathom.com). If you were following along here you can probably guess what the next two modules is going to be.

**Comment by jhabdas** [comment]
Version `5.0.0` of After Dark introduces a [module system](https://git.habd.as/comfusion/after-dark#module-system) which lays the foundation for various add-ons, the first of which the replacement of Google Analytics with [Fathom](https://usefathom.com). If you were following along here you can probably guess what one of the next two modules is going to be.
