### ISSUE TITLE
Implement Theme Inheritance

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#111]
Calling for a vote here as I'm considering porting theme from hackcss to [tailwindcss](https://github.com/tailwindcss/tailwindcss). [Y/n]?

**Comment by jhabdas** [comment]
@linuxlefty @MagicSword @MattMattV @guitmz @liara fyi

**Comment by linuxlefty** [comment]
Go for it :) It looks like tailwind would add new widgets and has better documentation. I'm assuming that this will be a breaking change? (which is fine with me)

**Comment by jhabdas** [comment]
> I'm assuming that this will be a breaking change if we're using classes from hackcss?

Yep, it'll be a major revision but hopefully worth the effort as I'm planning on giving the base theme a facelift in the process and help alleviate some user woes which AD sees feedback about now and then Re: CSS.

Once you get your hands on Tailwind I'm confident everyone will be impressed.

**Comment by linuxlefty** [comment]
Sweet! I can't wait to see your new design :+1:

**Comment by liara** [comment]
Tailwind looks promising at first glance. Haven't looked much into it, but I bet you did and I trust your decision.

Things, I suppose, that exsisting users reading this would like to know:
Will it make it easier for you to maintain the theme and for the users to customize it? 
Are you planning to change the looks much? 
Will this change need some intervention from the use's side? 

Maybe you could, for the users, who like it as it is, keep the after dark theme as it is and make this a new one named something like after dark enchanched or evolution or so:P

Anyway it is good to try something new and see how it evolves. So, go for it. :thumbsup:

**Comment by jhabdas** [comment]
> Maybe you could, for the users, who like it as it is, keep the after dark theme as it is and make this a new one [....]

I was thinking about this too. Even came up with a name for a second theme should it make sense to build: _Black Sunshine_. Once I get into the implementation I'll work on answering those questions for the user and produce a new theme if it makes sense. Otherwise a Classic mode will become available to keep the current look at feel, with as much backwards compatibility as possible.

**Comment by jhabdas** [comment]
For this feature we will leverage theme inheritance. After Dark remains the same look and feel and Black Sunshine becomes one of the new child themes.

https://github.com/gohugoio/hugo/issues/4460 @bep perfect timing on your splendid work

**Comment by pbuzdin** [comment]
Yes or tachyons.css

**Comment by guitmz** [comment]
Well go for it. I believe it will be nice :)

**Comment by jhabdas** [comment]
@pbuzdin I've looked at `tachyons` and was considering that until I learned about and took `tailwindcss` for a test drive. That said I want to thank those who chimed in. After considering feedback I've decided not to put the horse before the carriage and I'm going to produce a separate theme starting from scratch if a new css framework is going to be introduced.

Creating a new theme will give me room to experiment with theme inheritance while looking for refactoring opportunities in a new _base_ theme I may later decide to move After Dark onto. This approach is intended to keep AD in adherence with its KISS vision. Also, I don't want so start jamming features and redesigns down anyone's throats at this point to keep the codebase clean.

To be continued… Maybe.

**Comment by linuxlefty** [comment]
Sounds good, I look forward seeing to your new design :)

**Comment by jhabdas** [comment]
Theme inheritance was an idea I had to simplify some of the complexities users were having around customizing the hackcss theme. However, thanks to some new hugo features, I [was able](https://git.habd.as/comfusion/after-dark/src/branch/master/CHANGELOG.md#410-2018-07-19) to mitigate the need for any of this complexity, and greatly simplify the selection of a hackcss theme variant.

**Comment by guitmz** [comment]
@jhabdas I just updated my fork with your latest changes, its working pretty well and its also easier now. Great work! Many thanks :)
