### ISSUE TITLE
ATOM feeds using theme components

### ISSUE THREAD

**Issue by kaushalmodi** [comfusion/after-dark#114]
Since https://github.com/comfusion/after-dark/issues/32 was locked, I'd like to mention that one can add ATOM feed to any theme using the theme components feature in Hugo 0.42. 

Taking this theme as example, clone this extra theme (component) [`hugo-atom-feed`][1] in your themes dir, and change the `theme` parameter in site config to:

```toml
theme = ["hugo-atom-feed", "after-dark"]
```

and add "ATOM" to the page kinds where you want this custom output. 

[1]: https://github.com/kaushalmodi/hugo-atom-feed

**Comment by jhabdas** [comment]
Thanks for lifting the visibility on this. 🏋️

**Comment by jhabdas** [comment]
@kaushalmodi could you tag a topic on your repo so we can start organizing theme components?

`hugo-theme-component`

Thanks you berry much.

**Comment by kaushalmodi** [comment]
> could you tag a topic on your repo so we can start organizing theme components?

> hugo-theme-component

Hello, I have already done that as I said [here][1] :)

[1]: https://discourse.gohugo.io/t/theme-components-listing/12415/6?u=kaushalmodi
