### ISSUE TITLE
Archive page

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#15]
Before a pull will be accepted for archives it _must_ consider the following:

- [ ] Use of the `time` element with ISO 8601 `datetime` attribute ([example](https://github.com/comfusion/after-dark/blob/bc422b6cdbb55ba7f129ad48e904a3cdb43de219/layouts/partials/post/meta.html#L10-L11))
- [ ] Valid Schema Structured data defining relevant attributes of the article ([example](https://github.com/comfusion/after-dark/blob/4eea0836df50815151471cc029b85ad4d83e89b5/layouts/post/single.html#L8)) ([validator](https://search.google.com/structured-data/testing-tool))
- [ ] Post reading time and date in DRY fashion using the same logic provided for post meta in content summaries in lists and singles ([example](https://github.com/comfusion/after-dark/blob/master/layouts/partials/post/meta.html))
- [ ] Markup rendered must be valid HTML5 ([validator](https://html5.validator.nu/))

**Stretch goals:**

- [ ] Static [Article Grouping](https://gohugo.io/templates/list#grouping-content) filters providing archive segmentation options atop the content view.
- [ ] Refactor existing `partials/post/meta` as needed into existing post list pages with special consideration for learnings from implementing a _Content View_.

**Comment by vbrandl** [comment]
I think this isn't a job the theme has to solve. This feature should actually be included in hugo itself or you include it on your own.
Have a look at his repository:
https://gits.quark.business/david/collantes.us/src/master/layouts/archive
and
https://gits.quark.business/david/collantes.us/src/master/content/archives.md
Using these two files I was able to reproduce the archive for my own blog on https://www.vbrandl.net/archive

**Comment by jhabdas** [comment]
> I think this isn't a job the theme has to solve. 

I agree and disagree. On one hand we have minimalism, YAGNI. On the other we have pragmatism. Most users will want an archive page if their actively blogging. Given that fact, coupled with the current pagination which is, and will remain, simple, I'm going to err on the side of pragmatism here and introduce the archives page as an opt-in feature (similar to the short codes I've started adding), and an item of discovery for the user.

**Comment by desi3o** [comment]
Really good idea 👍

**Comment by jhabdas** [comment]
Feature to be implemented at 15 thumbs

**Comment by jhabdas** [comment]
Also, for those still on After Dark. I've been working on a stealth project to add [PhotoSwipe](http://photoswipe.com/). Once I wrap up [Hyperdrive](https://github.com/comfusion/hyperdrive), which actually exists because of [an innovation](https://hackcabin.com/post/managing-async-dependencies-javascript/) I stumbled on while integrating PhotoSwipe into Hack Cabin, I'll get back to not just to creating this archives page but a full blown image gallery with deep linkable full-screen images with _sexy_ touch support (click the above PhotoSwipe link to see what I mean).

Here are some teaser stills:

![screen shot 2017-06-05 at 10 22 21 pm](https://cloud.githubusercontent.com/assets/440298/26787714/95d24186-4a3d-11e7-855a-cbace016cfd4.png)
![screen shot 2017-06-05 at 10 22 27 pm](https://cloud.githubusercontent.com/assets/440298/26787715/960b5444-4a3d-11e7-8450-8f9bd7aad91e.png)

**Comment by ibewatuwant** [comment]
I'm trying to gwt into my google after dark not working codes failing

**Comment by jhabdas** [comment]
@ibewatuwant when you say `gtw` are you referring to [google web toolkit](http://www.gwtproject.org/), or something different? if you'd like to open an issue please feel free - going to need more info though to provide any useful help.

**Comment by jhabdas** [comment]
I have to admit, I'm having fun trying to decipher that last message. Are you saying you're trying to <q>get into google</q>? In other words, have your After Dark site listed on Google Search using [Webmaster Verifications](https://github.com/comfusion/after-dark/#webmaster-verification) feature?

**Comment by jhabdas** [comment]
Closing for lack of interest. May circle back on this later but a search feature would probably eliminate the need for this feature.
