### ISSUE TITLE
Add meta kewords

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#19]
Suggestion and example implementation from @Sly777 in https://github.com/comfusion/after-dark/pull/14. This feature will be useful for page scrapers and less sophisticated search engines looking to enter the search market and compete for world dominance.

**Comment by Sly777** [comment]
I will send it today

**Comment by Sly777** [comment]
https://github.com/comfusion/after-dark/pull/20

**Comment by jhabdas** [comment]
closed by https://github.com/comfusion/after-dark/commit/4b1f0f1ae2785fc636d84380a8f803d0e689f5e7
