### ISSUE TITLE
Firefox doesn't render icon for external links

### ISSUE THREAD

**Issue by vbrandl** [comfusion/after-dark#22]
The Firefox browser doesn't seem to render the icon that is shown after links to external websites. There is just a empty space.
![Example](https://i.imgur.com/WZLKZBc.png)
The screenshot was made in a fresh Firefox 52.0.2 64-bit profile on a Arch Linux 64-bit system

**Comment by jhabdas** [comment]
@vbrandl thanks for reporting. It's also not showing up in `elinks` either. The CSS voodoo that's going on there is a little complex for the browser. I'll look into it as soon as I can, as I'm not happy with the current experience (or the fact there are spaces appearing in place of the icon in `.Summary` content. /cc @fastidious

**Comment by vbrandl** [comment]
Firefox for Android has the same problem when rendering the page.

**Comment by jhabdas** [comment]
@vbrandl Updated initial comment with workaround. If it doesn't remove the spacing you're seeing as-is, use [specificity](http://devdocs.io/css/specificity) to give the custom override more strength.

**Comment by vbrandl** [comment]
Yes that removed the space for Gecko based browsers. Thanks.
FYI: webengine and webkit are working fine. Lynx won't show the icon but also won't show the space after the link so it seems to handle everything fine.

**Comment by jhabdas** [comment]
@vbrandl Thanks for the info. One of the primary goals of this theme is to provide inclusive (a.k.a. universal design both in modern browser but in terminal browsers as well. I'll let you know when the issue is resolve and a patch is released.

**Comment by jhabdas** [comment]
@vbrandl all set /cc @fastidious on implementation

**Comment by vbrandl** [comment]
I just updated the theme to the current version but when running `hugo serve`, I get the following errors:
```
ERROR 2017/04/13 11:54:57 Error while rendering "page": template: /home/me/hugo/test2/themes/after-dark/layouts/post/single.html:35:7: executing "/home/me/hugo/test2/themes/after-dark/layouts/post/single.html" at <partial "critical-ve...>: error calling partial: Partial "critical-vendor.css" not found
ERROR 2017/04/13 11:54:57 Error while rendering "page": template: /home/me/hugo/test2/themes/after-dark/layouts/_default/single.html:35:7: executing "/home/me/hugo/test2/themes/after-dark/layouts/_default/single.html" at <partial "critical-ve...>: error calling partial: Partial "critical-vendor.css" not found
ERROR 2017/04/13 11:54:57 Error while rendering "taxonomyTerm": template: /home/me/hugo/test2/themes/after-dark/layouts/_default/terms.html:35:7: executing "/home/me/hugo/test2/themes/after-dark/layouts/_default/terms.html" at <partial "critical-ve...>: error calling partial: Partial "critical-vendor.css" not found
ERROR 2017/04/13 11:54:57 Error while rendering "taxonomy": template: /home/me/hugo/test2/themes/after-dark/layouts/_default/taxonomy.html:35:7: executing "/home/me/hugo/test2/themes/after-dark/layouts/_default/taxonomy.html" at <partial "critical-ve...>: error calling partial: Partial "critical-vendor.css" not found
ERROR 2017/04/13 11:54:57 Error while rendering "section": template: /home/me/hugo/test2/themes/after-dark/layouts/_default/list.html:35:7: executing "/home/me/hugo/test2/themes/after-dark/layouts/_default/list.html" at <partial "critical-ve...>: error calling partial: Partial "critical-vendor.css" not found
ERROR 2017/04/13 11:54:57 Error while rendering "home": template: /home/me/hugo/test2/themes/after-dark/layouts/index.html:35:7: executing "/home/me/hugo/test2/themes/after-dark/layouts/index.html" at <partial "critical-ve...>: error calling partial: Partial "critical-vendor.css" not found
```

**Comment by jhabdas** [comment]
@vbrandl https://github.com/comfusion/after-dark/issues/28
