### ISSUE TITLE
Demo on theme site is broken

### ISSUE THREAD

**Issue by digitalcraftsman** [comfusion/after-dark#30]
The homepage of the [theme's demo](https://themes.gohugo.io/theme/after-dark/) mainly shows CSS and the original (unstyled) content.

**Comment by jhabdas** [comment]
You're on a theme frenzy, @digitalcraftsman. Thanks for the note. This should be resolved with #29, which closes #28. I'm making some tweaks and should be done in a few.

**Comment by digitalcraftsman** [comment]
Thanks for the update. And Bjørn was already a step ahead of me in #28. Let me once you're done and I'll update the themes list.

> You're on a theme frenzy, @digitalcraftsman.

Could you elaborate that a bit further? :wink:

**Comment by jhabdas** [comment]
Closed by https://github.com/comfusion/after-dark/commit/eba70c975c2a81a0af7d52beb2fe1aaf148d3d50

> Could you elaborate that a bit further?

I started watching the hugoThemes repo recently and say a flurry of activity leading up to this. I'm very happy @bep was able to fix the issue _and_ find a backwards compatible approach. Very awesome.
