### ISSUE TITLE
Atom web feeds

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#32]
## Required upvotes

~~15~~ _voting closed_

## Feature

Hugo [provides](https://gohugo.io/templates/rss/) RSS but Atom is preferable for use with After Dark. Atom isn't some [flash in the pan web syndication format](https://jsonfeed.org). Atom is IETF standard, battle tested and resolves issues in RSS 2.0 such as date formatting, better i18n and affords multiple enclosures to name a few.

A successful pull should:

- [ ] Add spec compliant atom web feed template to theme
- [ ] Provide summaries with `.Summary` using user-defined excerpts
- [ ] Distinguish content type (e.g. post or page content)
- [ ] Normalize output with `feed.xml` from [`jekyll-feed`](https://github.com/jekyll/jekyll-feed)
- [ ] Expose feed meta to base template using [`rel=alternate`](http://devdocs.io/html/link_types#alternate)
- [ ] Use a valid MIME type and set feed language based on config
- [ ] Consider use of `prev` and `next` rel attributes, and how to handle items in a collection/series
- [ ] Consider providing a top-level digest using [out of line content](http://www.datypic.com/sc/atom/t-atom_atomOutOfLineContentType.html)
- [ ] Provide Open Graph image data in feed syndication where appropriate
- [ ] Suppress output of RSS 2.0
- [ ] Avoid use of custom XML namespaces for (even [media rss](http://www.rssboard.org/media-rss))

And possibly:

- [ ] Add digital signatures, [encryption support](https://www.w3.org/TR/2002/REC-xmlenc-core-20021210/) for feeds produced?
- [ ] Provide support for `enclosure`s?

Resources:

https://tools.ietf.org/html/rfc5023 - IETF spec for Atom 1.0
http://www.intertwingly.net/wiki/pie/Rss20AndAtom10Compared - Atom v. RSS
https://www.ibm.com/developerworks/library/x-atom10/index.html - Friendly Atom intro
http://www.datypic.com/sc/atom/s-syndication.xsd.html - Quick reference for Atom spec
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fscripter.co%2Fatom.xml - Validator

**Comment by jhabdas** [comment]
I opened this initially thinking I'd forgotten to add web feeds because I didn't add `rel=feed`, which, upon further inspection, is entirely not true. We web feed `rel=alternate` right in the base template. [According to WHATWG](https://blog.whatwg.org/tag/rel#rel-feed) `rel=feed`, though it's in the HTML5 spec, was originally proposed in 2005 with regards to Atom and somehow slipped into the spec. It's entirely unnecessary given we already have a way to link to web feeds in the `head` and will likely be deprecated in a future version of XML. Why do I mention it? Because the Hugo docs showed it in addition to `rel=alternate` and, as a result, many thousands of websites will have it. But not After Dark. Because After Dark is _beyond_ web standards.

The issue then morphed into "Hey, why not support Atom", which is in reflection is a noble desire, but entirely not going to happen because it would violate the After Dark design goal of _Deceptive Simplicity_.

If Atom is to be added, it must go through Hugo first. So anyone looking head to the discussion forums and get cracking.

**Comment by jhabdas** [comment]
Reviving this. RSS is terrible. And I mean simply terrible.

**Comment by marcisme** [comment]
Thanks for after dark!

I recently set up an atom feed, and I thought this information might be useful. I used [this gist](https://gist.github.com/lpar/7ded35d8f52fef7490a5be92e6cd6937) as a starting point.

These settings in `config.yaml` disable all RSS feeds and produce a single atom feed at `/feed/atom.xml`.

``` yaml
mediaTypes:
  application/atom:
    suffix: xml

outputFormats:
  Atom:
    mediaType: application/atom
    baseName: feed/atom

outputs:
  home:
    - HTML
    - Atom

disableKinds:
  - RSS
```

I couldn't find a good way to add something to the header section, so I just added the feed link to `layouts/partials/meta/theme-color.html`.

``` html
<meta name="theme-color" content="#000">
<link href="/feed/atom.xml" rel="alternate" type="application/rss+xml" title="{{ .Site.Title }}" />
```

This template at `layouts/index.atom.xml` should produce a feed that [validates](https://validator.w3.org/feed/#validate_by_input). The weirdness with the `CDATA` parts is apparently necessary due to a [bug](https://github.com/gohugoio/hugo/issues/1740) in go's libs.

``` html
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>{{ if eq  .Title  .Site.Title }}{{ .Site.Title }}{{ else }}{{ with .Title }}{{.}} on {{ end }}{{ .Site.Title }}{{ end }}</title>
  <link href="{{ .Permalink }}feed/atom.xml" rel="self"/>
  <link href="{{ .Permalink }}"/>{{ if not .Date.IsZero }}
  <updated>{{ .Date.Format "2006-01-02T15:04:05-07:00" | safeHTML }}</updated>{{ end }}
  <id>{{ .Permalink }}</id>{{ with .Site.Author.name }}
  <author>
    <name>{{.}}</name>{{ with $.Site.Author.email }}
    <email>{{.}}</email>{{end}}
  </author>{{end}}
  <generator>Hugo -- gohugo.io</generator>{{ range .Data.Pages }}
  <entry>
    {{ `<title type="html"><![CDATA[` | safeHTML }}{{ .Title }}]]></title>
    <link href="{{ .Permalink }}"/>
    <id>{{ .Permalink }}</id>{{ with .Site.Params.Author }}
    <author>
      <name>{{.}}</name>
    </author>{{end}}
    <published>{{ .Date.Format "2006-01-02T15:04:05-07:00" | safeHTML }}</published>
    <updated>{{ .Lastmod.Format "2006-01-02T15:04:05-07:00" | safeHTML }}</updated>
    {{ `<content type="html"><![CDATA[` | safeHTML }}{{ .Content | html }}]]></content>
  </entry>{{ end }}
</feed>
```

**Comment by jhabdas** [comment]
@marcisme thank you for this valuable information

**Comment by jhabdas** [comment]
Waiting to hear from Hugo maintainers on https://github.com/gohugoio/hugo/issues/3473. Hugo should be using Atom, not pushing sites to upgraded to an IETF standard superseding RSS 2.0.

**Comment by jhabdas** [comment]
@marcisme Updated the OP with a few resources you may find interesting if you haven't seen them yet. Some are obvious finds. The others felt like striking gold.

**Comment by lpar** [comment]
Should `range .Data.Pages` be `range first 15 .Data.Pages`, or does Hugo automatically limit the range?

**Comment by stapelberg** [comment]
> Should `range .Data.Pages` be `range first 15 .Data.Pages`

Yes, thanks :).

> , or does Hugo automatically limit the range?

It does not.

**Comment by jhabdas** [comment]
Thanks to @lingxz we now have an example Atom feed [cooked into](https://github.com/lingxz/er) a Hugo theme

**Comment by kaushalmodi** [comment]
I have an [Atom feed template][1] that generates [valid ATOM feed][2] (example from my site).

[1]: https://gitlab.com/kaushalmodi/hugo-theme-refined/blob/master/layouts/_default/list.atom.xml
[2]: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fscripter.co%2Fatom.xml

**Comment by jhabdas** [comment]
@kaushalmodi thanks for sharing. This is great. Validator linked much appreciated. Saves digging.

**Comment by jhabdas** [comment]
Based on upvotes received and how long this has been open I'm calling this a `wontfix` as there doesn't seem to be strong support and AD and RSS2 just kinda make sense together in an oldskool kinda way. I'm pleased the information gathered here was valuable to others implementing Atom in their Hugo themes and, as a result I'll leave this open for visibility.

**Comment by jhabdas** [comment]
As @kaushalmodi points out in #114 an Atom webfeed may be added to After Dark with nary more than a one liner thanks to a theme component they made. Hugo 0.42+ required.
