### ISSUE TITLE
Support for AMP, Instant Articles, Apple News, Twitter Card?

### ISSUE THREAD

**Issue by maxpopo** [comfusion/after-dark#35]
Support for:

[ ]  [AMP Project](https://www.ampproject.org/)
[ ] RSS Feeds for Instant article [Facebook Instant Articles](https://developers.facebook.com/docs/instant-articles/publishing/setup-rss-feed)
[ ] [Apple News](https://help.apple.com/newspublisher/icloud/#/)
[ ] [Twitter Card](https://dev.twitter.com/cards/overview)

Any ideas?

**Comment by jhabdas** [comment]
@maxpopo Check out [Hugo Content Types](https://gohugo.io/content/types/) and let me know if you can suggest any specific theme changes you feel could facilitate any of the above once you have a working demonstration I can review. Thanks for your contribution.

**Comment by jhabdas** [comment]
Apologies. That was not what I meant to send. One moment. :)

**Comment by jhabdas** [comment]
http://gohugo.io/extras/output-formats/

Basically, create an MVP using one of the above with After Dark, let me study it and then I can give better direction on support. Cheers and I hope you are enjoying After Dark.
