### ISSUE TITLE
What are you struggling with?

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#38]
Opening a thread to collect feedback. Good. Bad. Ugly. What are you struggling with? Let 'er rip.

**Comment by tmhorne** [comment]
I can't seem to figure out how to use a variant.

**Comment by jhabdas** [comment]
@tmhorne Happy to lend a hand. Would you mind describing in a little more detail what you'd like to achieve so I may try and provide some guidance?

**Comment by jhabdas** [comment]
P.s. I've got 2am staring at me on my clock, so it may be a few hours before my next reply.

**Comment by tmhorne** [comment]
I just wanted to use the hack.css solarized-dark theme.

So I went to /themes/after-dark and ran "npm i".
I then cp'ed /themes/after-dark/node_modules/hack/dist/solarized-dark.css to /themes/after-dark/layouts/partials/critical-vendor.css. I did make a backup of the file first.
I opened /config.toml and added 'theme_variant' = "standard solarized-dark"
Finally, I ran hugo -t after-dark. But then everything turned white.

So I tried variations on the theme. I tried 'theme_variant' = "solarized-dark".

I tried putting the original critical-vendor.css back and instead copied the file to /layouts/partials/critical-vendor.css. (and both of the theme_variants I tried earlier). Same result.

I tried using critical-custom.css instead. Looks like the default theme instead of the "solarized-dark" theme.

**Comment by jhabdas** [comment]
Thanks for the info, @tmhorne. I just ran this on a fresh install and followed your instructions (and not mine) and here's what I see:

<img width="1287" alt="screen shot 2017-05-20 at 11 06 00 am" src="https://cloud.githubusercontent.com/assets/440298/26272499/8f6a5a84-3d4c-11e7-993b-ad1354f97cbb.png">

**Observations**

- If Hugo is not automatically regenerating files it must be restarted before the changes will appear. In my case, this is what happened in a first-time user experience. So that's an area for improvement.
- It's not totally clear where to drop theme-related files when opening `critical-theme.css`, something which could be resolved by a couple of well-placed code comments.
- I'm still not happy with the number manual parts of this process. Those can be improved with some scripts to better automate the steps. But this is usually a one-time deal so there's not a lot of value yet trying to automate this.

@tmhorne Could you approach this one more time with confidence it will work and let me know what observations you make to help identify the gray spots I'm overlooking conceptually?

**Comment by jhabdas** [comment]
I'm going to take a wild guess and suppose you saw the white screen due to:

> It's not totally clear where to drop theme-related files when opening critical-theme.css, something which could be resolved by a couple of well-placed code comments.

When modifying `critical-theme.css`, please ensure only the bottom portion (where the `.hack` starts on the first column of the file) is replaced and let me know if that doesn't solve your problem.

**Comment by phanan** [comment]
For me, I can't get the theme work at all. Several weeks ago I installed After Dark and it worked just fine, but after switching to a new computer today and reinstalling After Dark following the new instructions (elinks? flying-toasters?), my site is now totally blank.

**Comment by jhabdas** [comment]
> You can see my repo here: https://github.com/phanan/til

Taking a look.

**Comment by phanan** [comment]
Thanks! Just pushed a new commit with the theme properly (?) and manually pulled into `themes` dir. Now it says 

```
Error: Unable to locate Config file. Perhaps you need to create a new site.
       Run `hugo help new` for details. (Config File "config" Not Found in "[/Users/an.phan/github/til/themes]")
```

when I attempt to `hugo serve`.

**Comment by jhabdas** [comment]
@phanan Just a couple of things to point out:

- Getting started is only to get started the first time you set-up. It's intended to bootstrap a new site, and that's it. So your `flying-toasters` stuff isn't necessary, and can be removed.
- However, I noticed your `config.toml` file does not contain After Dark configuration, so I'm not sure how you had the site running.
- Short of any additional coaching, simply try this:
  - Revert to commit before introducing any new changes
  - `cd themes` from your project root
  - Replace `after-dark` folder with content of release you were using when you installed. Releases are available here: https://github.com/comfusion/after-dark/releases

**Comment by phanan** [comment]
Thanks @jhabdas. Previous I would do a `hugo serve --theme=after-dark`, so maybe that's the reason why I didn't need any After Dark related config in `config.toml`. Will try your suggestions later today and let you know.

**Comment by jhabdas** [comment]
@phanan Sounds good. If you haven't customized the theme you could start fresh with the getting started instructions and simply copy the contents of your `content/post` directory from your existing site into the fresh copy of the latest release, follow the on-screen instructions and then simply run with `hugo serve` after including your current `config.toml` settings into the new site and you should be golden. Please let me know how you like the new getting started experience.

**Comment by phanan** [comment]
I can confirm reverting to v1.6.1 works. Thanks @jhabdas!

**Comment by jhabdas** [comment]
Holla
