### ISSUE TITLE
Issue generating post content on Arch Linux

### ISSUE THREAD

**Issue by ChrisFernandez** [comfusion/after-dark#39]
hugo -v -t after-dark
INFO 2017/05/26 14:36:42 Using config file: 
INFO 2017/05/26 14:36:42 using a UnionFS for static directory comprised of:
INFO 2017/05/26 14:36:42 Base: /home/fernandez/Personal/hispagatos.org/themes/after-dark/static
INFO 2017/05/26 14:36:42 Overlay: /home/fernandez/Personal/hispagatos.org/static/
INFO 2017/05/26 14:36:42 syncing static files to /home/fernandez/Personal/hispagatos.org/public/
WARN 2017/05/26 14:36:42 No translation bundle found for default language "en"
WARN 2017/05/26 14:36:42 Translation func for language en not found, use default.
WARN 2017/05/26 14:36:42 i18n not initialized, check that you have language file (in i18n) that matches the site language or the default language.
Started building sites ...
INFO 2017/05/26 14:36:42 found taxonomies: map[string]string{"tag":"tags", "category":"categories"}
ERROR 2017/05/26 14:36:42 Error while rendering "page": template: /home/fernandez/Personal/hispagatos.org/themes/after-dark/layouts/post/single.html:27:9: executing "main" at <partial "post/byline...>: error calling partial: template: theme/partials/post/byline.html:14:65: executing "theme/partials/post/byline.html" at <sort .>: error calling sort: can't sort string

**Comment by jhabdas** [comment]
Thanks for the report @ChrisFernandez. Toss me your "hugo version" string (including platform build info) and I'll try and repro in the next 24 hours.

**Comment by ChrisFernandez** [comment]
```
hugo version
Hugo Static Site Generator v0.21 linux/amd64 BuildDate: 2017-05-22T15:35:04-07:00
```
is on [BlackArch GNU/Linux](https://github.com/BlackArch/blackarch) based on Arch Linux

**Comment by jhabdas** [comment]
I'll stand up a box soon. Thanks for the report. Installed from PPA, snap or source?

**Comment by ChrisFernandez** [comment]
> I'll stand up a box soon. Thanks for the report. Installed from PPA, snap or source?
Just regular arch gnu/linux install method
`pacman -S hugo`
been using it with another theme... I am switching to yours :)

**Comment by ChrisFernandez** [comment]
@jhabdas Any luck?

**Comment by jhabdas** [comment]
@ChrisFernandez Just getting settled in. I'm on +08:00 UMT but will give this a go as soon as I iron out some GPL licensing changes needed in comfusion/hyperdrive.

**Comment by jhabdas** [comment]
😅 Okay, done with the licensing matters. Picking this up for investigation.

**Comment by jhabdas** [comment]
Don't hold your breath. Might be a moment:

<img width="388" alt="screen shot 2017-05-27 at 7 01 50 pm" src="https://cloud.githubusercontent.com/assets/440298/26520930/0e1325ba-430f-11e7-9cac-5e5d3e6f7b5f.png">

**Comment by jhabdas** [comment]
Looks like they have a container. Will try standing up in DO.

**Comment by jhabdas** [comment]
`line 23: make: command not found`

Haha. Damn. This is one scrappy install. Almost done installing Hugo from the French Yogurt thingie.

**Comment by jhabdas** [comment]
Built up an Arch box for Hugo install using docker image - https://hub.docker.com/r/base/archlinux/
Installed Hugo using `yaourt -S hugo` -  https://gohugo.io/overview/installing/

Ran install script after installing `hugo` and `elinks` and saw the following when finished:

<img width="826" alt="screen shot 2017-05-27 at 8 16 01 pm" src="https://cloud.githubusercontent.com/assets/440298/26521372/9ba4faa2-4319-11e7-8609-17fd154d8b0e.png">

Here's the build of Hugo I was using:

    [jhabdas@535832d4e9bb ~]$ hugo version
    Hugo Static Site Generator v0.21 linux/amd64 BuildDate: 2017-05-27T12:13:40Z

Looking at the error from the OP looks like the system is choking on the `sort` in the `byline.html`. I put post bylines under flag via config. @ChrisFernandez could you try setting `hide_author = true` in your config and then run `hugo serve` and let me know if that helps?

Aside, that particular line of code is the one which is preventing me from going multilingual and I have some open discussion regarding it on the Hugo discussion forums but haven't had a strong need to adjust it yet.

**Comment by jhabdas** [comment]
Not sure what I was smoking when I said to try using `hide_author`. That was dumb. This is the sorting stuff in the byline:

```
  {{ with .Params.categories }}
    in <span itemprop="articleSection">{{ delimit (apply (apply (sort .) "partial" "post/category-link.html" ".") "chomp" ".") ", " " and " }}</span>
  {{ end }}
  {{ with .Params.tags }}
    and tagged {{ delimit (apply (apply (sort .) "partial" "post/tag-link.html" ".") "chomp" ".") ", " " and " }}
  {{ end }}
```

These are the lines which output delimited lists of categories and tags on a per-post basis in the post byline, regardless of whether or not `hide_author` is set via config, and look like this:

<img width="780" alt="screen shot 2017-05-28 at 11 30 27 am" src="https://cloud.githubusercontent.com/assets/440298/26525919/1c46f460-4399-11e7-995a-956841a9761a.png">

To temporarily disable the sort statements in the byline without config they can be overridden on a file-by-file basis from the `layouts` directory. In the case of the byline, it can be tested on your current machine without sorting by doing:

```
cd ~/Personal/hispagatos.org/
mkdir -p layouts/partials/post/ && cd $_
touch byline.html && echo "scooby snacks" >> byline.html
cd ~/Personal/hispagatos.org/
hugo -v -t after-dark
```

**Comment by ChrisFernandez** [comment]
Awesome. seems that this work around does the trick! :) updating our blog now as I write this.

**Comment by jhabdas** [comment]
Groovy. The file contents of `byline.html` be overwritten to whatever you like (e.g. copying from same file in theme and removing the `(sort .)` statements). Here's the related discussion on the hugo forums related to that line WRT going multilingual

https://discuss.gohugo.io/t/creating-taxonomic-link-partial-for-multilingual-translations/6416

**Comment by ChrisFernandez** [comment]
BTW thanks for been so fast and responsive <3

**Comment by jhabdas** [comment]
@ChrisFernandez fyi - hispagatos.org TLS cert expired yesterday
