### ISSUE TITLE
Lazy load does not work on list page / home

### ISSUE THREAD

**Issue by engyii** [comfusion/after-dark#46]
The intelligent lazy loading is based on the presence of the 'lazyload' css class in the .Content variable.  This variable is empty on post list and home page preventing any content with lazy loading to be displayed properly on these kinds of page.

I've remove the regex condition for now. 
```
{{ $lazylist := findRE "class=\".*?\\blazyload\\b.*?\"|class=lazyload\b" .Content }}<!-- http://regexr.com/3f9d1 -->
    {{ if ge (len $lazylist) 1 }}
```
not sure how to correct this test in a clean way to make this work.

**Comment by jhabdas** [comment]
Thanks for sharing your workaround for lazy-loading on the homepage, Enguerrand.

At present your current implementation removes the [*Intelligent* aspect of the lazy-loader](https://github.com/comfusion/after-dark#intelligent-lazy-loading) implementation, and will force and extra HTTP request and bytes down the wire for every single page no matter if it uses images or not. 

For your use case, my suggestion would be to instead to add a `script` to pull in the JavaScript to the specific templates you're confident will always use lazy loading. This is not built into After Dark by default as it would violate the _Deceptive Simplicity_ goal set out in the docs.

I hope you are enjoying After Dark. If you have a site you would like to show off please let me know the location and I will add it to the After Dark wiki along with the others.

**Comment by jhabdas** [comment]
One more thing. If you can find a way to enable lazyloading on the homepage while keeping the script from downloading on pages without images I'm game to discuss the approach and consider taking a PR.
