### ISSUE TITLE
Support for standalone mobile AMP pages

### ISSUE THREAD

**Issue by demoxo** [comfusion/after-dark#66]
[AMP on Google Search guidelines](https://support.google.com/webmasters/answer/6340290?hl=en)

[AMP HTML Specification](https://www.ampproject.org/docs/reference/spec)

> However, publishers often speculate that Google favors AMP pages in search, so Outside’s experience is noteworthy because it wasn’t penalized by Google for dropping AMP. A Google spokesperson said publishers’ search rankings are not affected by whether a publisher uses AMP.

[Source](https://digiday.com/media/outside-magazine-increased-pageviews-per-visit-13-percent-ditching-google-amp/)

Optional: [Combine AMP with Progressive Web Apps](https://www.ampproject.org/docs/guides/pwa-amp)

**Comment by jhabdas** [comment]
Thanks for the suggestion @demoxo. AMP isn't going to happen on After Dark unless it becomes a Web Standard. Google has a track record of introducing and then deprecating some [very problematic](https://developers.google.com/webmasters/ajax-crawling/docs/specification) tech to the Web. Given After Dark is minimalist it's already wicked quick on its own, and will evolve with Web standards as the Web pushes forward.

That said please feel free to create a fork! And feel free to burn the license file while your at it! Har Har.
