### ISSUE TITLE
Swap Google Analytics for Matomo

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#67]
I just received an email from Google after logging into Google Analytics on my new iPhone. It was a cross sell spam message and said ”Welcome to your new iPhone. Here are some other products we detected you might enjoy.” One of the other products was YouTube, which they've banned me from so it's obvious there's little to no intelligence behind their spam messages.

With this issue we will look at dropping Google Analytics for something more privacy-minded.

**Comment by jhabdas** [comment]
Front-runner: https://github.com/matomo-org/matomo

**Comment by jhabdas** [comment]
After a closer look at mamato it's unsuitable as it requires individual hosting and AD users are unlikely to want to do this. keen.io is an alternative but Google is used by most and so this entire issue is a violation of the pareto principle. closing as `wontfix`.

**Comment by pbuzdin** [comment]
You can try https://metrica.yandex.com/

**Comment by jhabdas** [comment]
@pbuzdin thank you so very much. Opening a new issue now! <3
