### ISSUE TITLE
Spacing Issue?

### ISSUE THREAD

**Issue by xnaas** [comfusion/after-dark#70]
When looking at [your website](https://hackcabin.com/), I can see there's a significant amount of spacing between "Read More" and the next title.

![your example](https://user-images.githubusercontent.com/8271327/34442261-8b175b14-ec86-11e7-8d27-bfb469539d83.png)

But, when looking at my own site, even _without_ any modifications to the source of After Dark, the spacing is...well...missing, basically.

![my example](https://user-images.githubusercontent.com/8271327/34442283-b784e1ee-ec86-11e7-9ea2-81a3d087853c.png)

**Comment by jhabdas** [comment]
@xnaas thanks for pointing that out. as I was pushing the theme forward in my hackcabin.com prototype not all code has made it back into the main theme yet. if you see something like that you can investigate by opening up a developer console and inspecting the css after selecting the code near the area which looks visually wrong.

<img width="478" alt="screen shot 2018-01-17 at 7 42 18 pm" src="https://user-images.githubusercontent.com/440298/35041276-d096151e-fb49-11e7-957e-a9ef16e1b3f2.png">

looking at the above I see I forgot to check in a style rule when I added the `readmore` class to the `nav` link bumping up visually against the header below it.
