### ISSUE TITLE
Complete Twitter Card Support

### ISSUE THREAD

**Issue by sudopluto** [comfusion/after-dark#76]
Afaik, twitter cards have an another layer on top of ogp. Goal is to have https://cards-dev.twitter.com/validator return a complete card (with image). Again will work on this once I get my site up and running.

**Comment by jhabdas** [comment]
I'd like to see this. Tagging issue. PRs welcome.

**Comment by jhabdas** [comment]
@sudopluto twitter cards now available in [`3.6.0`](https://github.com/comfusion/after-dark/blob/master/CHANGELOG.md#360-2018-03-22)
