### ISSUE TITLE
support math (via katex?)

### ISSUE THREAD

**Issue by sudopluto** [comfusion/after-dark#77]
fast math support could be added via katex.

a version without node could use the cdn version of katex for support, but that is not as performant as doing server side rendering

i think mmark would have to be used as the markdown processor since it works better with inline latex

again i will probably get on this after setting up my website.

**Comment by jhabdas** [comment]
I left some info in #75 which should help you progress. After installation the `static` directory is open to you to add any `js` files you wish. Then simply override the theme's layout files at the site-level.

If I plan to introduce a breaking change to layout organization later I'll bump the major in the package manifest so users can vendor `after-dark` using `npm` or `yarn` with version control.

https://github.com/Khan/KaTeX looks cool, but I don't believe a majority of users would find benefit in having it. That doesn't mean adding it is not planned for. This kind of theme customization has been built into Hugo. Here's the documentation to do it: https://gohugo.io/themes/customizing/

Regarding the Markdown processor that sounds more like Hugo thing so you may want to ask around on their forums and poke around the Hugo github repository.

As mentioned in #75 please feel free to fork and customize everything to your liking and continue bouncing ideas off me—having input from other users helps.
