### ISSUE TITLE
[Question] Custom personalization issue ?

### ISSUE THREAD

**Issue by k0pernicus** [comfusion/after-dark#87]
Hello there,

I am trying to modify the style of `<em>` tags, creating a `critical-custom.css` file in `layouts/partial/head`, but it seems the modifications don't work...
Indeed, even the following CSS code 
```
body {
    background-color: red;
}
```
does not modify the style of the `body` tag...
I think I missed something in the doc but I don't know what.

Is it possible to know how to add custom personalization to HTML tags please? :-)

Thanks in advance!

**Comment by k0pernicus** [comment]
Ok, I found (with the help of @rsommerard, thanks again) how to override in a web browser console how to override the style for `em` tag:
```
.hack em:before {
    content:"";
  }
.hack em:after {
    content:"";
}
.hack em {
    font-weight: bold;
}
```

Now, when I saved this CSS code into `critical-custom.css`, nothing changed, and the style does not appear in the web browser console...
Is there any change to override the existing CSS with custom personalization code?

**Comment by k0pernicus** [comment]
Closed: renamed `partial` to `partials` and... yeah... so... yeah.
Thanks @rsommerard 
Voilà

**Comment by jhabdas** [comment]
Sorry you had this issue @k0pernicus. That's a nasty little gotcha and super hard to spot. Nevertheless I'm glad you got it and that's to @rsommerard for helping out.

**Comment by jhabdas** [comment]
After Dark `4.1.0` [introduces](https://git.habd.as/comfusion/after-dark/src/branch/master/CHANGELOG.md#410-2018-07-19) a feature to disable `hackcss` to help make issues like this easier to spot.
