### ISSUE TITLE
Remove PrivacyTube Shortcode

### ISSUE THREAD

**Issue by jhabdas** [comfusion/after-dark#89]
https://pastebin.com/CD5R0tgy

Caught it using a script loader to download and execute a minified JS file unexpectedly. My hosts file override blocked the download but this seems like an obvious security and privacy concern so it needs to be removed.

<img width="527" alt="screen shot 2018-04-16 at 4 40 40 pm" src="https://user-images.githubusercontent.com/440298/38798744-fdd17b2c-4194-11e8-96d5-a2753db2ab08.png">

Please comment on the following Reddit if you know anything: https://www.reddit.com/r/privacy/comments/8clrzn/google_your_backdoor_to_the_internet/

Thanks.

**Comment by jhabdas** [comment]
Going to ignore this for now unless I hear noise.

**Comment by jhabdas** [comment]
https://github.com/gohugoio/hugo/issues/4616#issuecomment-386776676

**Comment by jhabdas** [comment]
Another option is to block content by default unless user gives consent like DuckDuckGo does with YouTube videos. But that seems like a cop-out. I'm nuking this shortcode and removing and working to removing #92 Frugal Analytics by default for the sake of privacy.

**Comment by onedrawingperday** [comment]
Regarding the youtube-nocookie I checked your link at [https://hackcabin.com/mine/build/3-coin-8-gpu-gtx1060-mining-rig/](https://hackcabin.com/mine/build/3-coin-8-gpu-gtx1060-mining-rig)/

I'm still not seeing the XSS errors in the console you mentioned [here](https://github.com/gohugoio/hugo/issues/4616#issuecomment-386776676) Also I'm not seeing YouTube cookies/local storage being set on page load.

Try clearing your cookies or viewing the page in an incognito tab and see for yourself.

**Comment by jhabdas** [comment]
@onedrawingperday no cookies. worse. a script loader which does whatever it wants.

**Comment by onedrawingperday** [comment]
@jhabdas 
Ok. I can see that script being loaded on your page from: https://www.google.com/js/bg/nkomCc3znx-Y45_0PQ9TlhpBELZbFiE9JPG9huGRwjM.js

But it seems that you already have other scripts on your page like this one (I think it's Google AdWords related): 

```
<script>
var trackOutboundLink = function(url) {
   ga('send', 'event', 'outbound', 'click', url, {
     transport: 'beacon',
     hitCallback: function(){}
   })
}


var trackReferralLink = function(url) {
   ga('send', 'event', 'referral', 'click', url, {
     transport: 'beacon',
     hitCallback: function(){}
   })
}
</script>
```
But honestly I see no scripts being loaded on a clean HTML page with just an embed from youtube-nocookie.

**Comment by jhabdas** [comment]
@onedrawingperday yep you found it. there's more info about it linked from a nice person in the reddit link above if you're curious what Google might be doing. as for the other links you found those are actually not part of the theme just some cruft I had laying around to fix following tearing off the bandaid of deleting my google account earlier this year (no more Gmail, AdSense, Maps, yadda yadda).

I'm going to leave this issue open in case more information surfaces as the GDPR stuff plays out. Looking today I see Google may be playing shifty-domain with some of their scripts and some of them are loading from a non-google domain today.

**Comment by jhabdas** [comment]
Looks like Hugo `0.41` has some privacy enhanced stuff now so this shortcode will definitely be removed in a future version. https://gohugo.io/about/hugo-and-gdpr/

**Comment by onedrawingperday** [comment]
There is still work to be done. But for now I suggest you use the `privacyEnhanced` mode in Privacy Config to use to `youtube-nocookie`

**Comment by jhabdas** [comment]
Thanks @onedrawingperday. And thank you so much for all the work you've done for the community.

**Comment by jhabdas** [comment]
I'm going to leave this in for now so I can compare it with the changes coming from the GDPR updates made to Hugo base shortcodes. Making as `wontfix` but that might change later.
