### ISSUE TITLE
Reading time and search problems

### ISSUE THREAD

**Issue by usererror** [comfusion/after-dark#95]
Hey there! I'm new to Hugo and After Dark so bear with me... I'm trying to setup a simple site using the theme, haven't really changed much yet. Two things I've noticed are weird that I can't seem to fix:

1. Every article has a 0 minute estimated reading time and says "with 0 words" at the bottom regardless of how long it actually is
2. I enabled search following the instructions in the README but it doesn't seem to actually find anything :(

Are there any other steps or config options I missed?

**Comment by usererror** [comment]
Looks like reading times are working now but search is still wonky.

**Comment by jhabdas** [comment]
@usererror the reading time was a regression in Hugo 40.1 and was fixed in 40.2. As for search, I've noticed some wonky behavior too. Such is the way things often are when JavaScript is involved. Do you think it could be a race condition (e.g. #90) or are you able to reproduce the behavior you're experiencing consistently?

**Comment by usererror** [comment]
I could definitely see js being a thorn in static environments :)

I don't think it's a race condition due to slow networking because the issue is present when running `hugo server` and going over `localhost`. Could that be part of the issue? I assume with the way hugo works it wouldn't matter.

To detail exactly what I'm seeing:
1. I go to `/search/` from the lazy menu up top
2. Hit s to start searching
3. Type in "hugo" (I have an article called "hugo test", tagged "hugo" and "test", with a body of "hugo test")
4. A small 'x' appears to the right to clear the search but no results show. Hitting enter etc. does nothing as far as I can tell.

**Comment by jhabdas** [comment]
Thanks for the info @usererror. Sorry for your troubles. I missed a step while putting the instructions together! Could you try again with https://github.com/comfusion/after-dark/commit/3c8d87ac214347063633d8ac0315ea99651f88db and re-open if you have any more difficulties. Thanks so much.

**Comment by usererror** [comment]
Just wanted to confirm that fix seems to work -- my search looks good now! Thanks!
